spring:
  config:
    import: classpath:application-common.yml

  datasource:
    url: jdbc:mysql://${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate

logging:
  config: classpath:logback-prod.xml

jwt:
  token:
    secret: ${TOKEN_SECRET_KEY}
    access-expiration-ms: 900000  # 15분
    refresh-expiration-ms: 1209600000  # 14일
